### ISSUE TITLE
Hephaestus Temples not showing

### ISSUE THREAD

**Issue by Saxxonknight** [mklabs/tw-troy-mod-temples-list#1]
No temples of Hepaestus show in list, they are under No Temples mixed with regions that truly don't have one.

**Comment by mklabs** [comment]
Hey @Saxxonknight thank you for opening the issue, and my apologies for not noticing it.

Seems like I fixed that in September with the 1.2 version https://github.com/mklabs/tw-troy-mod-temples-list/releases/tag/1.2.0
